/**
 * Every user-facing string, in French. Keep the UI free of hard-coded text.
 */
export const t = {
  marque: 'NEXA',
  intro: {
    accroche: 'Votre histoire commence ici.',
    entrer: 'Entrer',
    chargement: 'Le monde s’éveille…',
  },
  oeuf: {
    attente: 'Quelque chose vous attend…',
    toucher: 'Touchez l’œuf',
    encore: 'Encore…',
    presque: 'Il bouge !',
    naissance: 'Votre Nexa est né.',
    nommer: 'Donnez-lui un nom',
    nomParDefaut: 'Nexa',
    confirmerNom: 'C’est son nom',
    passer: 'Plus tard',
  },
  barre: {
    niveau: 'Niv.',
    xp: 'XP',
    pieces: 'Éclats',
    menu: 'Menu',
  },
  actions: {
    nourrir: 'Nourrir',
    jouer: 'Jouer',
    explorer: 'Explorer',
    evolution: 'Évolution',
  },
  menu: {
    codex: 'Codex',
    boutique: 'Boutique',
    amis: 'Amis',
    reglages: 'Réglages',
    journal: 'Journal',
    fermer: 'Fermer',
  },
  commun: {
    fermer: 'Fermer',
    retour: 'Retour',
    bientot: 'Bientôt',
    futur: 'Fonctionnalité future',
    simulation: 'Simulation',
    demo: 'Démonstration',
    confirmer: 'Confirmer',
    annuler: 'Annuler',
    continuer: 'Continuer',
    recuperer: 'Récupérer',
  },
  nourrir: {
    titre: 'Nourrir',
    sousTitre: 'Chaque aliment nourrit une affinité.',
    appetit: 'Appétit',
    rassasie: 'Repu. L’appétit revient dans',
    vide: 'Plus de cet aliment. La ration quotidienne arrive demain.',
    rareTrouve: 'Les aliments rares se trouvent en explorant.',
  },
  jouer: {
    titre: 'Lueurs',
    consigne: 'Touchez les lueurs avant qu’elles ne s’éteignent.',
    commencer: 'Commencer',
    pret: 'Prêt ?',
    fin: 'Fini !',
    lueurs: 'lueurs attrapées',
    recompenseReduite: 'Votre Nexa est un peu fatigué : récompense réduite.',
    pleineForme: 'Pleine forme : récompense complète.',
    prochaine: 'Pleine forme dans',
    trouve: 'Trouvé en jouant :',
    doubler: 'Multiplier ×2',
    doublerDetail: 'Publicité récompensée (simulation)',
    pubTitre: 'Publicité simulée',
    pubTexte: 'Aucune vraie publicité n’est diffusée dans cette version.',
    pubFermer: 'Récupérer ma récompense',
  },
  explorer: {
    titre: 'Explorer',
    demoTitre: 'Carte de démonstration',
    demoTexte:
      'Cette carte est fictive. Le monde réel arrivera avec la géolocalisation : aucune vraie rue ni position n’est utilisée ici.',
    positionDemo: 'Votre position (démonstration)',
    coffre: 'Coffre',
    coffreProche: 'Ouvrir le coffre',
    coffreLoin: 'Approchez-vous',
    coffreRecharge: 'Coffre déjà ouvert. Retour dans',
    lieu: 'Lieu',
    decouvrir: 'Découvrir',
    decouvert: 'Découvert',
    evenement: 'Événement',
    presence: 'Présence',
    presenceTexte: 'Un autre Nexa, quelque part. Le mode social arrive plus tard.',
    seDeplacer: 'Se déplacer ici',
    miniJeuTitre: 'Synchronisez le sceau',
    miniJeuConsigne: 'Touchez au moment où l’anneau croise le sceau.',
    reussi: 'Le coffre s’ouvre.',
    rate: 'Le sceau résiste. Réessayez.',
    recompenses: 'Récompenses',
    meteoReelle: 'Météo réelle',
    meteoActiver: 'Activer la météo réelle',
    meteoExplication:
      'NEXA demande votre position au navigateur, l’arrondit au kilomètre, interroge le service météo et ne conserve jamais vos coordonnées.',
    meteoRefusee: 'Position refusée. La météo reste inconnue, le jeu continue normalement.',
    meteoErreur: 'Service météo injoignable pour le moment.',
    meteoActualiser: 'Actualiser',
    meteoDesactiver: 'Désactiver',
  },
  evolution: {
    titre: 'Votre Nexa évolue avec vous.',
    dominante: 'Affinité dominante',
    inconnue: '???',
    tendances: 'Tendances',
    indice: 'Indices',
    prochainIndice: 'Prochain indice au niveau',
    voies: 'Cinq voies',
    equilibre: 'Aucune voie ne domine encore.',
    voile: 'Voilé',
    revele: 'Révélé',
  },
  codex: {
    titre: 'Codex',
    decouvertes: 'découvertes',
    inconnu: 'Inconnu',
    categories: {
      creatures: 'Créatures',
      formes: 'Formes',
      mutations: 'Mutations',
      objets: 'Objets',
      accessoires: 'Accessoires',
      decouvertes: 'Découvertes',
    },
  },
  boutique: {
    titre: 'Boutique',
    sousTitre: 'Éclats gagnés en jouant. Aucun achat réel dans cette version.',
    acheter: 'Acheter',
    equiper: 'Équiper',
    equipe: 'Équipé',
    possede: 'Possédé',
    insuffisant: 'Pas assez d’éclats',
    premium: 'Premium · achat réel non disponible',
    categories: {
      auras: 'Auras',
      socle: 'Décorations du socle',
      colliers: 'Colliers',
      ornements: 'Ornements',
      environnements: 'Environnements',
    },
  },
  amis: {
    titre: 'Amis',
    intro: 'Le mode social est en préparation. Voici ce qui arrivera.',
    ajouter: 'Ajouter un ami',
    visiter: 'Visiter sa créature',
    comparer: 'Comparer les évolutions',
    missions: 'Missions communes',
    jumelage: 'Jumelage de deux Nexa',
    jumelageTexte: 'Deux joueurs unissent leurs Nexa : œuf partagé, variante, mutation ou récompense rare.',
    activites: 'Activités du monde réel',
    activitesTexte: 'Marche, sport, tâches du quotidien, défis en famille. NEXA valorise ce que vous accomplissez.',
  },
  reglages: {
    titre: 'Réglages',
    son: 'Ambiance sonore',
    sonDetail: 'Désactivée par défaut. Aucun fichier audio n’est encore fourni.',
    meteo: 'Météo réelle',
    reinitialiser: 'Réinitialiser la partie',
    reinitialiserConfirm: 'Tout effacer et recommencer depuis l’œuf ?',
    version: 'Prototype V1',
  },
  journal: {
    titre: 'Journal',
    vide: 'Rien encore. Votre histoire s’écrit.',
  },
  niveau: {
    titre: 'Niveau supérieur',
    texte: 'grandit.',
    recompense: 'éclats',
  },
  periodes: {
    aube: 'Aube',
    jour: 'Jour',
    crepuscule: 'Crépuscule',
    nuit: 'Nuit',
  },
  meteo: {
    inconnu: 'Météo inconnue',
    soleil: 'Soleil',
    nuageux: 'Nuageux',
    pluie: 'Pluie',
    orage: 'Orage',
    neige: 'Neige',
    chaleur: 'Fortes chaleurs',
    froid: 'Froid',
  },
  humeurs: {
    calme: 'calme',
    heureuse: 'heureuse',
    curieuse: 'curieuse',
    endormie: 'endormie',
    affamee: 'affamée',
  },
  dev: {
    titre: 'Développement',
    periode: 'Période',
    auto: 'Auto',
    meteo: 'Météo',
    niveau: 'Niveau',
    xp: '+100 XP',
    affinites: 'Affinités',
    recharges: 'Réinitialiser les recharges',
    eclosion: 'Rejouer l’éclosion',
    reset: 'Effacer la sauvegarde',
  },
} as const
